#!/usr/bin/env python3
"""Generate passthrough bindings for the libnvisp_v3 wrapper.

Input:  exports_func.tsv  -- TSV dump of the real library's FUNC exports
        (columns: addr, size, type, bind, vis, shndx, name), as produced by
        tools/expdump.
Output: gen_passthrough.h -- included once from nvisp_shim.c. Contains:
          - one writable slot per exported function (dlsym target);
          - one naked ARM/Thumb stub per function that tail-jumps to the slot;
          - the name/slot table used by the constructor.

Regenerate after the export list changes:
    python3 gen_passthrough.py exports_func.tsv gen_passthrough.h

The stub is deliberately minimal: it touches nothing, performs a tail jump,
so every register (r0-r3, ip) and the whole argument stack reach the real
function unchanged. dlsym returns Thumb addresses with bit0 set; `bx r12`
performs the interworking jump. If a slot is unresolved the constructor
points the stub at shim_trap (SIGILL: loud, finds its way into a tombstone).
"""
import sys

tsv, out_path = sys.argv[1], sys.argv[2]

names = []
for line in open(tsv):
    cols = line.rstrip('\n').split('\t')
    if len(cols) < 7 or cols[2] != 'FUNC':
        continue
    names.append(cols[6])

with open(out_path, 'w') as f:
    f.write('/* GENERATED by gen_passthrough.py from exports_func.tsv.'
            ' Do not edit. */\n\n')
    # slots
    for n in names:
        f.write('void *shim_slot_%s;\n' % n)
    f.write('\n')
    # stubs (file-scope asm; symbols are global by default)
    for n in names:
        f.write(
            '__asm__(\n'
            '    ".text\\n"\n'
            '    ".align 2\\n"\n'
            '    "%(sym)s:\\n"\n'
            '    "  ldr r12, 1f\\n"\n'
            '    "  bx  r12\\n"\n'
            '    "  .align 2\\n"\n'
            '    "1: .word shim_slot_%(sym)s\\n");\n'
            'extern void %(sym)s(void);\n' % {'sym': n})
    f.write('\n')
    # the name/slot table for the constructor
    f.write('static const struct shim_binding shim_bindings[] = {\n')
    for n in names:
        f.write('    { "%(n)s", &shim_slot_%(n)s },\n' % {'n': n})
    f.write('    { 0, 0 },\n')
    f.write('};\n')

print('names: %d' % len(names))
